[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "8NVA8HLgC9e3G4VgdfEAxPGeomNZgHFQGaAXDZsgYjHV"
dice_game = "GKQtwjgpGFQXyEmFHxarsmDqpgbPwq9VoaVydVsv91Kn"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
